export const PHASES = {
  ROUND_START: 'ROUND_START',
  ACTION_COMPARE: 'ACTION_COMPARE',
  HIT_CHECK: 'HIT_CHECK',
  ON_HIT: 'ON_HIT',
  DAMAGE_RESOLVE: 'DAMAGE_RESOLVE',
  APPLY_DAMAGE: 'APPLY_DAMAGE',
  TAKE_DAMAGE: 'TAKE_DAMAGE',
  DEATH_CHECK: 'DEATH_CHECK',
  ROUND_END: 'ROUND_END',
  BATTLE_END: 'BATTLE_END',
};

export const BATTLE_OUTCOME = {
  CONTINUE: 'CONTINUE',
  WIN: 'WIN',
  LOSE: 'LOSE',
};

export const ACTOR_SCOPE = {
  BOSS: 'BOSS',
  PLAYER: 'PLAYER',
  OTHERS: 'OTHERS',
  SYSTEM: 'SYSTEM',
};

export const ACTOR_BUCKET = {
  [ACTOR_SCOPE.BOSS]: 0,
  [ACTOR_SCOPE.PLAYER]: 1,
  [ACTOR_SCOPE.OTHERS]: 2,
  [ACTOR_SCOPE.SYSTEM]: 3,
};
