export const ROUND_START_ORDER = {
  CLEAR_DISABLED_ACTIONS: 100,
  POPCORN_GAIN: 1200,
  HAPPY_FLOWER_GAIN: 1300,
  RELIC_LEVER: 1400,
  RELIC_DELEGATION_PROBLEM_GAIN: 1450,
  RELIC_SILENCE_GOLD: 1500,
  NSYC_EKAI_PENDING_DAMAGE: 1600,
  NSYC_STACK_GAIN: 1700,
};

export const COMBAT_ORDER = {
  RESOLVE_SELECTED_ACTIONS: 100,
  HIT_CHECK: 100,
  ON_HIT_DAMAGE: 100,
};

export const DAMAGE_ORDER = {
  RELIC_DESTINED_FIRST_SIGHT: 1100,
  RELIC_POSSIBLE_REUNION_CHARGE: 1200,
  ON_DAMAGED_COMMON: 1200,
  RELIC_POSSIBLE_REUNION_BONUS_DAMAGE: 1300,
  BOSS_FAULT_ROBOT_OVERLOAD_ROUND_END: 1800,
  SYSTEM_APPLY_HP_CHANGE: 9000,
};

export const DEATH_ORDER = {
  SAVED_BY_BLADE: 1200,
  DEFAULT_DEATH_RESOLUTION: 9000,
};
